[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lammps-trajectory-analysis-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "jupyterlab>=4.5.7",
    "matplotlib>=3.10.9",
    "mdanalysis>=2.10.0",
    "mdanalysistests>=2.10.0",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "scipy>=1.17.1",
    "mypy>=2.2.0",
    "pytest>=9.1.1",
    "h5py>=3.16.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["lammps_trajectory_analysis_tools*"]


